### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by 000xs**
# Hey there! Here is your checklist for your Hackaccino submission:

> If you're participating in an **offline** Hackaccino workshop, you don't need to make a pull request. Please ask the organizer for a submission form.

## Author name

**Author:** 000xs

## Live Website Link

**Link:** https://3d-music-player.vercel.app/

## Code

**GitHub Link** https://github.com/000xs/3d-music-player

## Hack Club Slack ID

> Find your Slack ID by visiting the [#what-is-my-slack channel](https://hackclub.slack.com/archives/C0159TSJVH8) on Hack Club Slack. If you're not on Hack Club Slack, please join [here](https://hackclub.com/slack).

ID: U07EBTWK3CH

## Check off the items that are true.

- [x] You’re in high school or under 18.
- [x] This is your first time participating in Hackaccino (YSWS).
- [x] The README.md is placed in the `/submissions/<your-name>/` [directory](https://github.com/hackclub/hackaccino/tree/main/submissions).
- [x] The code you’ve provided is open-source.
- [x] The code you are submitting was written by you.
- [x] The live URL you’ve provided is working.

> Thank you for your PR!

### CODE REVIEW

**Comment by arnavravinder** [comment]
Hi, It doesn't seem to work? Could you rectify this please :)

**Comment by 000xs** [comment]
> Hi, It doesn't seem to work? Could you rectify this please :)

It works! Here's how to do it:

Click anywhere on the webpage.
Drag the cursor (a red circle in the middle) to the button.
Click the button (refer to the button guide provided for details).

[3d Music Player.webm](https://github.com/user-attachments/assets/f1b6cf9a-1eb8-4785-850e-6188b9065e30) 

Note: The video did not capture the file browsing and audio.
 
Please try this yourself to ensure it works as intended.

**Comment by arnavravinder** [comment]
Unfortunately this is too basic. Could you add some more elements like album art, song info, and preloaded songs? Thanks :)

**Comment by 000xs** [comment]
> Unfortunately this is too basic. Could you add some more elements like album art, song info, and preloaded songs? Thanks :)
 ok i will upgrade those things !

**Comment by 000xs** [comment]
> Unfortunately this is too basic. Could you add some more elements like album art, song info, and preloaded songs? Thanks :)

@arnavravinder

I Updated My Project , can u Re-Review That?

**Comment by arnavravinder** [comment]
This is fantastic—thank you so much for your submission! 🎉 
If you're a teen, you can get your Frap here: [forms.hackclub.com/fraps](http://forms.hackclub.com/fraps) ;)

**Pull request merged**
