### PR TITLE
Add FrameIt project

### PR DESCRIPTION
**Pull request by Gabriele73**
## Author name

**Author:** Gabriele

## Live Website Link

**Link:** https://gabriele73.github.io/FrameIt/

## Code

**GitHub Link**  https://github.com/Gabriele73/FrameIt

## Hack Club Slack ID 

> Find your Slack ID by visiting the [#what-is-my-slack channel](https://hackclub.slack.com/archives/C0159TSJVH8) on Hack Club Slack. If you're not on Hack Club Slack, please join [here](https://hackclub.com/slack).

ID: U083850176D

## Check off the items that are true.

- [x] You’re in high school or under 18.
- [x] This is your first time participating in Hackaccino (YSWS).
- [x] The README.md is placed in the `/submissions/<your-name>/` [directory](https://github.com/hackclub/hackaccino/tree/main/submissions).
- [x] The code you’ve provided is open-source.
- [x] The code you are submitting was written by you.
- [x] The live URL you’ve provided is working.

> Thank you for your PR!

### CODE REVIEW

**Review by yednapg — CHANGES_REQUESTED** [review]
Hey! Thank you so much for your PR! It looks great so far. I think adding a bit more detail to your website could make it even better. For example, you could turn it into a math website where you display math formulas along with the 3D objects.

Let me know once you've updated it, and I'll be happy to review it again!

**Comment by Gabriele73** [comment]
Like. turning math formulas into 3d objects?

**Comment by yednapg** [comment]
I’m sorry for the late reply. I was suggesting that you could build a classroom board where you can display all your 3D elements and write down how to calculate their area, perimeter, and circumference below them.

**Comment by yednapg** [comment]
Feel free to open another pull request!

**Pull request closed without merging**
